/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTimelineRouteImport } from './routes/_app/timeline'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSchedulerRouteImport } from './routes/_app/scheduler'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAgentRouteImport } from './routes/_app/agent'
import { Route as AppSettingsEnergyRouteImport } from './routes/_app/settings.energy'
import { Route as AppGoalsGoalIdRouteImport } from './routes/_app/goals.$goalId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulerRoute = AppSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsEnergyRoute = AppSettingsEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppGoalsGoalIdRoute = AppGoalsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => AppGoalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/agent': typeof AppAgentRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRouteWithChildren
  '/review': typeof AppReviewRoute
  '/scheduler': typeof AppSchedulerRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/timeline': typeof AppTimelineRoute
  '/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/settings/energy': typeof AppSettingsEnergyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/agent': typeof AppAgentRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRouteWithChildren
  '/review': typeof AppReviewRoute
  '/scheduler': typeof AppSchedulerRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/timeline': typeof AppTimelineRoute
  '/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/settings/energy': typeof AppSettingsEnergyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/goals': typeof AppGoalsRouteWithChildren
  '/_app/review': typeof AppReviewRoute
  '/_app/scheduler': typeof AppSchedulerRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/_app/settings/energy': typeof AppSettingsEnergyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/agent'
    | '/dashboard'
    | '/goals'
    | '/review'
    | '/scheduler'
    | '/settings'
    | '/timeline'
    | '/goals/$goalId'
    | '/settings/energy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/agent'
    | '/dashboard'
    | '/goals'
    | '/review'
    | '/scheduler'
    | '/settings'
    | '/timeline'
    | '/goals/$goalId'
    | '/settings/energy'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_app/agent'
    | '/_app/dashboard'
    | '/_app/goals'
    | '/_app/review'
    | '/_app/scheduler'
    | '/_app/settings'
    | '/_app/timeline'
    | '/_app/goals/$goalId'
    | '/_app/settings/energy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scheduler': {
      id: '/_app/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AppSchedulerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/energy': {
      id: '/_app/settings/energy'
      path: '/energy'
      fullPath: '/settings/energy'
      preLoaderRoute: typeof AppSettingsEnergyRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/goals/$goalId': {
      id: '/_app/goals/$goalId'
      path: '/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AppGoalsGoalIdRouteImport
      parentRoute: typeof AppGoalsRoute
    }
  }
}

interface AppGoalsRouteChildren {
  AppGoalsGoalIdRoute: typeof AppGoalsGoalIdRoute
}

const AppGoalsRouteChildren: AppGoalsRouteChildren = {
  AppGoalsGoalIdRoute: AppGoalsGoalIdRoute,
}

const AppGoalsRouteWithChildren = AppGoalsRoute._addFileChildren(
  AppGoalsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsEnergyRoute: typeof AppSettingsEnergyRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsEnergyRoute: AppSettingsEnergyRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRouteWithChildren
  AppReviewRoute: typeof AppReviewRoute
  AppSchedulerRoute: typeof AppSchedulerRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTimelineRoute: typeof AppTimelineRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRouteWithChildren,
  AppReviewRoute: AppReviewRoute,
  AppSchedulerRoute: AppSchedulerRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTimelineRoute: AppTimelineRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
